Task_1_1_3
FedorBrykin/OOP pull request #3
Opened 2024-09-19 16:15 UTC by FedorBrykin

2024-09-20 05:06 UTC, galinabykova requested changes

2024-09-20 05:06 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/brykin/Expression.java
> +    public abstract String print();
для вывода в строку есть специальный метод, определённый в Object, toString, лучше переопределить его

2024-09-20 05:06 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/brykin/Variable.java
> +    public int eval(String variableAssignments) {
мне тут не очень нравится, что у тебя парсинг происходит здесь. Если будет 1000 вхождений  переменных, весь словарь 1000 раз будет парситься. Мне кажется, лучше будет строку один раз распарсить в Выражении, а дальше передавать уже мапку
```java
abstract class Expression {
    //...
    
    public double eval(String s) {
        return evaluate(stringToMap(s));
    }
    
    private HashMap<String, Double> stringToMap(String s) {
        // ...
        return new HashMap<String, Double>();
    }
    
    abstract protected double evaluate(HashMap<String, Double> dict);
}

class Value extends Expression {
    private String name;
    
    @Override
    protected double evaluate(HashMap<String, Double> dict) {
        return dict.get(name);
    }
}

class Mul extends Expression {
    private Expression left;
    private Expression right;
    
    @Override
    protected double evaluate(HashMap<String, Double> dict) {
        return left.evaluate(dict) + right.evaluate(dict);
    }
}
```

2024-09-20 05:06 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/brykin/Parser.java
> +        for (int i = 0; i < expression.length(); i++) {
а почему надо бить на два цикла (не поняла прост)?

2024-09-20 05:06 UTC, galinabykova commented on Task_1_1_3/src/test/java/ru/nsu/brykin/MainTest.java
> +        e.print();
наверно, тут нужен какой-то ассёрт, иначе эта строчка в никуда возвращается

2024-09-20 05:06 UTC, galinabykova commented on Task_1_1_3/src/test/java/ru/nsu/brykin/MainTest.java
> +        System.setIn(in);
кажется, строчки с перехватом ввода не нужны

2024-09-20 05:06 UTC, galinabykova commented on Task_1_1_3/src/test/java/ru/nsu/brykin/MainTest.java
мне не нравится, как у тебя разбиты тесты. В одном тесте ты проверяешь, всё для одного выражение, и в выводе тестов будет непонятно, в каком именно методе класса ошибка. Лучше сделать для каждого класса свой класс тестов. Также помимо стандартных ситуаций надо рассмотреть крайние случаи

2024-09-20 06:02 UTC, FedorBrykin commented on Task_1_1_3/src/test/java/ru/nsu/brykin/MainTest.java
> +        e.print();
Так он там есть. Только ниже

2024-09-20 06:06 UTC, galinabykova commented on Task_1_1_3/src/test/java/ru/nsu/brykin/MainTest.java
> +        e.print();
но он не проверяет результат работы print, ассёрт ниже не зависит от этой строчки
если здесь не планировалось проверять работу ассёрта, нужно удалить эту строчку. Сейчас выглядит так, будто она здесь есть, чисто, чтобы покрытие поднять

2024-09-21 05:22 UTC, galinabykova requested changes
нужны отдельный тесты на каждый публичный метод  каждого класса-наследника, а не только add и mul

2024-09-21 05:22 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/brykin/Add.java
> +    public String toString() {
сюда нужно добавить аннотацию Override. С ней компилятор проверит, что этот метод переопредён

2024-09-21 05:22 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/brykin/Variable.java
> +    public double evaluate(HashMap<String, Double> dict) {
нужно прописать в документации не совсем интуитивно понятную особенность, как твой метод ведёт себя, если переменная в словаре не найдена. И сделать на это тест

2024-09-22 05:55 UTC, galinabykova requested changes
reviewdog

2024-09-22 05:55 UTC, galinabykova commented on Task_1_1_3/src/test/java/ru/nsu/brykin/AddTest.java
> +        de.print();
assert ниже не проверяет результат работы print, ассёрт ниже не зависит от этой строчки
если здесь не планировалось проверять работу ассёрта, нужно удалить эту строчку. Сейчас выглядит так, будто она здесь есть чисто, чтобы покрытие поднять

2024-09-22 05:55 UTC, galinabykova commented on Task_1_1_3/src/test/java/ru/nsu/brykin/MulTest.java
> +        e.print();
аналогично print в add

2024-09-22 05:55 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/brykin/Parser.java
повысь нв этом файле покрытие до 80%

2024-09-22 13:36 UTC, galinabykova requested changes
reviewdog

2024-09-23 06:43 UTC, galinabykova approved these changes

2024-09-23 06:59 UTC, merged